# Codecov configuration: ignore non-Ruby assets and generated files so PR coverage focuses on Ruby code
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 75

ignore:
  - "app/assets/**"
  - "app/javascript/**"
  - "public/**"
  - "db/**"
  - "config/**"
  - "vendor/**"
  - "features/**"
  - "coverage/**"

# Optionally treat ERB/template files as not relevant for coverage reporting
paths:
  - +app/**/*.rb
  - +lib/**/*.rb
